# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20181021_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='voted_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='award.Project'),
        ),
    ]
